// Storage for the arrays from which to choose the sentence parts.
var fortuneTeller = {
    firstPart: ["You ","I ","We "],
    secondPart: ["earned ", "crushed ", "deserved "],
    thirdPart: ["this dream!", "the job!", "this goal!"],
};

// Functions for getting a random number of the array length and return it to an variabl.
let selectFirst = () => {
    let selectFirstPart = Math.floor(Math.random() * fortuneTeller.firstPart.length);
    return selectFirstPart;
};
let selectSecond = () =>{
    let selectSecondPart = Math.floor(Math.random() * fortuneTeller.secondPart.length);
    return selectSecondPart;
};
let selectThird = () => {
    let selectThirdPart = Math.floor(Math.random() * fortuneTeller.thirdPart.length);
    return selectThirdPart;
};


// The sentence is generated by accessing object arays at the previously randomly generated and saved indexes in relation to their array length.
const generatedSentence = fortuneTeller.firstPart[selectFirst()] + fortuneTeller.secondPart[selectSecond()] + fortuneTeller.thirdPart[selectThird()];

console.log(generatedSentence);

